### ISSUE TITLE
Broken code link

### ISSUE THREAD

**Issue by nranthony** [mgiacomelli/VirtualHE#1]
Hi, I hope the images treat you well.
Can you please check the http://web.mit.edu/mgg6/www/compiled_opengl_code.zip link in the readme, as it appears to be broken.
Thanks
Neil

**Comment by mgiacomelli** [comment]
I uploaded a copy to the repo itself, no point in having it as a separate download.  Also, I put a simple matlab example in as well just for completeness.  Let me know if you have any problems.
